[program:gunicorn]
command=sh scripts/entrypoint.sh
autostart=true
autorestart=true
startretries=999999
startsecs=10
stopasgroup=true
killasgroup=true
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/var/log/supervisor/%(program_name)s_stderr.log
stderr_logfile_maxbytes=10MB
stdout_logfile=/var/log/supervisor/%(program_name)s_stdout.log
stdout_logfile_maxbytes=10MB

[program:tail_stdout]
command=/bin/sh -c 'tail --follow=name /var/log/supervisor/gunicorn_stdout.log'
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0  ; Disable rotation
stderr_logfile_maxbytes=0  ; Disable rotation
stdout_logfile_backups=0
stderr_logfile_backups=0
autostart=true
autorestart=true
startretries=999999
startsecs=10

[program:tail_stderr]
command=/bin/sh -c 'tail --follow=name /var/log/supervisor/gunicorn_stderr.log'
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0  ; Disable rotation
stderr_logfile_maxbytes=0  ; Disable rotation
stdout_logfile_backups=0
stderr_logfile_backups=0
autostart=true
autorestart=true
startretries=999999
startsecs=10

[program:log_watcher]
command=python -m src.log_watcher
directory=/app
environment=PYTHONBUFFERED=1,PYTHONPATH=/app/src
autostart=true
autorestart=true
startretries=999999
startsecs=10
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/var/log/supervisor/%(program_name)s_stderr.log
stderr_logfile_maxbytes=10MB
stdout_logfile=/var/log/supervisor/%(program_name)s_stdout.log
stdout_logfile_maxbytes=10MB